M48
; DRILL file {KiCad 9.0.6} date 2026-02-25T03:50:00+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-25T03:50:00+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C8.400
%
G90
G05
T1
X90.0Y-47.0
X90.0Y-117.0
X165.0Y-47.0
X165.0Y-117.0
T2
X100.0Y-50.0
X100.0Y-113.0
X153.0Y-113.0
X154.0Y-50.0
M30
