M48
; DRILL file KiCad 10.0.0 date 2026-06-03T17:24:09
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-03T17:24:09+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X140.0Y-70.5
X160.0Y-70.5
T2
X110.0Y-55.0
X110.0Y-110.0
X185.0Y-75.0
X185.0Y-110.0
M30
