M48
; DRILL file {KiCad 9.0.6} date 2026-03-15T18:50:03+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-15T18:50:03+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X162.339Y-142.93
X182.339Y-142.93
T2
X105.0Y-55.0
X105.0Y-145.0
X195.0Y-55.0
X195.0Y-145.0
M30
